export const meta = {
  name: 'ts4-speedkit-build-wave2',
  description: 'Build fast-mode pack, profile switcher, auto-merger/inbox, max-quality graphics fix; review each; then CLI + one-click launchers; then an end-to-end audit',
  phases: [
    { title: 'Build', detail: 'fastmode, profiles, merge/inbox, graphics-tuned' },
    { title: 'Review', detail: 'adversarial review + fix per component' },
    { title: 'Integrate', detail: 'CLI, one-click launchers, report, README' },
    { title: 'Audit', detail: 'end-to-end on a fake Sims tree incl. the other chat\'s mods_switch.py' },
  ],
}

const CONTEXT = `
PROJECT: "Sims 4 SpeedKit" at C:\\Users\\basim\\Tools\\sims4_speedkit - Python 3.12 desktop tools (stdlib + numpy only; no pip installs, no downloads) plus an in-game script mod, making The Sims 4 load faster and lag less for a user with a 259 GB mod library. THE USER WANTS: graphics kept at the highest quality but no lag; the game must stop taking forever to load; everything implemented and one-click - the user does not want to be asked anything or understand internals.

READ FIRST: research/research_results.json (research + skeptic 'corrections' - trust the corrections), research/wave1_results.json (what wave 1 built, reviewers' findings and integration notes), and docs/*.md. Existing modules (read them; DO NOT EDIT dbpf.py, library.py, journal.py - report bugs as findings instead):
- speedkit/dbpf.py: Package(path) (opens with FILE_SHARE_DELETE so others can rename meanwhile), PackageWriter, read_entries, open_shared, decompress, key_of, Entry(t,g,i unsigned,off,fsize,msize,comp,committed).
- speedkit/library.py: Library(db_path, roots) .scan() .packages() .scripts() .entries(pkg_id) .load_order(roots) .order_positions() .duplicated_keys() .winners(); SIMS/MODS/PARKED/ROOTS; game_running() (fails SAFE: True if it cannot tell). The overlay view lays Mods over Mods_parked at the same rel paths; if a rel exists in both, only the Mods copy counts.
- speedkit/journal.py: Journal(kind, note, home=SIMS\\SpeedKit, sims=SIMS, check_game=True, quarantine_home=None) .quarantine .put_new .replace .move; undo(id, home, check_game, dry_run) - plans everything first, resumable, dry-run safe, cross-drive quarantine OK (quarantine_home may be on E:), refuses homes inside Mods/Mods_parked, re-checks the game before every step, unique ids. .ts4script allowed only for kinds profile/inbox/install.
- speedkit/manifest.py (S4S merge manifest codec: build_flat, sources_of, rewrite_without, read_payload, MANIFEST_KEY), speedkit/companions.py (classify(lib) -> {pkg_id: Verdict(kind in core|addon|orphan|weak|tuning|cc|empty|broken, script, reasons)}, never_merge, load_order_sensitive, script_bearing_sources, script_modules), speedkit/game_index.py (GameIndex: has, ids_of_type, override_keys), speedkit/hashing.py + speedkit/dedup.py (plan/apply/report/undo of duplicate copies with an invariant check), speedkit/usedpack.py (scan_references of saves+Tray, plan/build/verify/is_stale of the 'CC my sims use' pack: ~54k keys / 7.0 GB / 4 packages, winner copies, EA default-replacement closure), speedkit/settings.py + speedkit/launch.py (graphics status/stock/preset/restore, Options.ini, caches, preflight memory report, launch with launch_time.json), speedkit/ingame_install.py + ingame/speedkit_monitor + tools/build_ingame.py (SpeedKit Monitor mod: load timer -> SIMS\\SpeedKit\\reports\\loadtimes.csv, 'speedkit.lag' profiler, CC guard warning when sims wear CC that is not loaded; reads SIMS\\SpeedKit\\profile_state.json {"profile": name}).
- The whole test suite passes: python -m unittest discover -s tests -p "test_*.py" (227 tests). Keep it passing.

CURRENT STATE OF THE USER'S FOLDERS (another Claude chat works in parallel on an animation mod and may launch the game or move files at any time):
- C:\\Users\\basim\\Documents\\Electronic Arts\\The Sims 4\\Mods holds the other chat's lean 'studio' set: scripts/TURBODRIVER_WickedWhims_Scripts.ts4script + scripts/TURBODRIVER_WickedWhims_Tuning.package, animation/WW_LAMABOY_Animation(s).package, FitStudio/ (its mod), Resource.cfg, desktop.ini. Everything else (sim/ = 189 merged CC packs 251 GB, scripts/*, Sliders/, Srsly Pack/, LittleMsSam Pack/, Scripts testing/, TMEX-Settings/, animation/anim1-5...) is parked in ...\\The Sims 4\\Mods_parked by the other chat's tool C:\\Users\\basim\\Tools\\sims4_fitstudio\\mods_switch.py (read it). Its manifest Mods_parked\\_manifest.json = {"moved": [rel paths relative to Mods, folders end with '/']}; 'lean' parks, 'full' moves every listed path back (skips one if something is already at the destination; tidies empty folders). Mods_parked\\_old_caches holds parked thumbnail caches (never mods).
- Facts: 755k CAS parts (614k unique) drive startup cost; catalog records are scattered through 250 GB of textures; RAM is very tight (Chrome 20 GB, 0.3-0.6 GB free at launch). Load order: first-loaded copy of a key wins; walk = depth-first NTFS order; '!' sorts first. 46 of the sim/ merged packs also contain script-mod tuning (920 S4S sources: stale WickedWhims tuning in m27, lot51 in m9, FallenCore, chingyu, WW animation snippets in anim1-5...).

HARD SAFETY RULES:
1. During development/testing NEVER write, move, rename or delete anything under "C:\\Users\\basim\\Documents\\Electronic Arts\\The Sims 4" or "E:\\The Sims 4", and never launch the game. Reading is fine (open packages via dbpf so renames are not blocked).
2. Tests that change files use a FAKE Sims tree under E:\\speedkit_test\\<component>\\ (copies of a few small real packages + synthetic ones) with Library(db_path=..., roots=...), Journal(home=..., sims=..., check_game=False). Clean up big scratch files.
3. Never call scan() on the shared data/library.sqlite; use a private copy (sqlite3 backup API from a read-only URI) for real-library dry runs.
4. Every change to the Sims folder goes through a Journal; real runs need an explicit apply flag; refuse while the game runs; never touch saves/Tray; never delete (quarantine); never modify .ts4script contents or companion packages.
5. Only create/edit your own component's files (+ tests/test_<component>*.py, docs/<component>.md). Unittest only (no pytest).
STYLE: plain readable Python, docstrings, small main() for CLI output, report real numbers from read-only dry runs on the real library.
`

const RESULT = {
  type: 'object',
  properties: {
    files: { type: 'array', items: { type: 'string' } },
    public_api: { type: 'string' },
    tests: { type: 'string' },
    real_library_numbers: { type: 'string' },
    limitations: { type: 'array', items: { type: 'string' } },
    notes_for_integration: { type: 'string' },
  },
  required: ['files', 'public_api', 'tests', 'limitations', 'notes_for_integration'],
}
const REVIEW = {
  type: 'object',
  properties: {
    findings: { type: 'array', items: { type: 'object', properties: {
      severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, what: { type: 'string' },
      evidence: { type: 'string' }, fixed: { type: 'boolean' }, fix: { type: 'string' } },
      required: ['severity', 'what', 'evidence', 'fixed'] } },
    tests_after: { type: 'string' },
    remaining_risks: { type: 'array', items: { type: 'string' } },
    verdict: { type: 'string', enum: ['ready', 'ready-with-caveats', 'not-ready'] },
  },
  required: ['findings', 'tests_after', 'remaining_risks', 'verdict'],
}

const COMPONENTS = [
  { key: 'fastmode', prompt: `COMPONENT "fastmode": speedkit/fastmode.py - decides and builds what the FAST profile loads so the game starts with ~1-2% of today's CAS parts while every sim, lot and script mod still works.
(1) park_set(lib, roots=('Mods','Mods_parked')) -> list of (root, rel) packages the fast profile leaves out: packages that are CAS-heavy CC catalogs (use CASP/texture/mesh share; in practice the sim/ merges and big standalone CAS CC files; small tuning/slider/preset/skin-DR packages stay). NEVER park: .ts4script files, packages classified core/addon/orphan/weak by speedkit.companions UNLESS they are S4S merged CC packs whose script content is only a small part (then park them and carry their script content in the fast pack, see 2b), the WickedWhims animation packs (animation/ folder), anything under FitStudio/, SpeedKit files. Return also a short reason per package.
(2) plan_pack(lib, refs, parked, kept) -> the FAST PACK keys (each with its exact source copy = the full-library winner, i.e. first in lib.load_order over both roots), the union of:
  (a) speedkit.usedpack's plan (CC worn by sims/lots in saves+Tray, with its closures and EA default-replacement closure) - call usedpack.plan and reuse its result;
  (b) every resource of a parked package that no kept package provides and that is NOT a CAS/BuildBuy asset: XML tuning of all types, SimData 0x545AC67A, STBL 0x220557DA, ASM/JAZZ 0x02D5DF13, CLIP 0x6B20C4F3/CLHD 0xBC4A5044 (animations), and any EA-override key (use speedkit.game_index.GameIndex.override_keys; covers default replacements of textures/meshes/tones too) - so scripts' tuning, animations and default replacements keep working;
  (c) CAS parts / objects referenced by tuning or SimData that stays loaded (kept packages + (b)): scan XML text for decimal/hex 64-bit ids and SimData for u64 values, intersect with CASP/OBJD instances in parked packages, and add them with their full closure (usedpack has the CASP TGI-list closure code - reuse it).
  Skip the S4S manifest type 0x7FB6AD8A and NameMap 0x0166038C. Report counts/bytes per part (a/b/c).
(3) build_pack(plan, out_dir=SIMS\\SpeedKit\\fastpack, max_package_bytes=1_900_000_000, dry_run=True, check_game=False) -> packages named '!!!!!SpeedKit_Fast_001.package'... (the '!' prefix makes them load FIRST, so each key's winner copy in the pack wins over any stale copy in a kept package, reproducing the full library's winners). Catalog-first order inside (CASP, THUM, TONE, OBJD, COBJ, SimData, XML, STBL, then meshes/textures/clips), bit-exact add_raw copies, fastpack.json recording sources, the saves/Tray fingerprints (usedpack's), the library fingerprint (sizes+mtimes of source packages) and counts. Writing into SIMS\\SpeedKit\\fastpack is outside Mods, so the game running does not matter for building (pass check_game=False there only). Also update_pack(...): if saves/Tray changed, compute the new plan and, when only a few keys are missing, write one extra '!!!!!SpeedKit_Fast_900+.package' delta instead of a full rebuild; full rebuild only when the library changed or the delta would exceed 500 MB. status(out_dir) -> fresh/stale + why.
(4) verify(...) -> keys the fast profile would be missing compared to the full library for what saves/Tray/tuning reference (should be only CC installed nowhere).
Measure on the real library (read-only, private DB copy): number of parked packages and GB, CAS parts loaded in fast mode vs full (count CASP index entries), pack keys/bytes by part (a/b/c). Build a real pack only into E:\\speedkit_test\\fastmode\\ (dry-run layout for the real thing is enough if space is short; E: has ~300 GB free), then delete the test pack.` },
  { key: 'profiles', prompt: `COMPONENT "profiles": speedkit/profiles.py - one-click profile switching that COEXISTS with the other chat's mods_switch.py.
Profiles: 'full' (every mod in Mods), 'fast' (everything except speedkit.fastmode.park_set(lib), plus the fast pack from SIMS\\SpeedKit\\fastpack placed at Mods root), 'studio' (exactly what mods_switch.py's KEEP list keeps - import its KEEP from C:\\Users\\basim\\Tools\\sims4_fitstudio\\mods_switch.py at runtime if present, else a built-in copy - plus SpeedKit_Monitor.ts4script). SpeedKit_Monitor.ts4script at Mods root is always kept in every profile.
Mechanics - SHARE the other tool's parking store and manifest format so both tools stay consistent: parked files live in Mods_parked at the same rel path and every parked path is listed in Mods_parked\\_manifest.json {"moved": [...]} exactly like mods_switch.py does (whole folders as 'dir/' when nothing inside is kept, else individual files). Read-modify-write the manifest atomically (tmp + os.replace), keep entries you did not create, and tolerate a malformed manifest (refuse with a clear message rather than crash). switch(profile, dry_run=True) computes the minimal moves from the current state (what is in Mods vs Mods_parked) to the target, moves through Journal kind 'profile' (same-drive renames), updates the manifest, moves the fast pack into Mods root (fast) or back to SIMS\\SpeedKit\\fastpack (other profiles), writes SIMS\\SpeedKit\\profile_state.json {"profile": name, "switched": iso time}, and quarantines localthumbcache.package when the loaded CC set changed (the research says to delete it after CC changes; quarantine instead). Scripts: a .ts4script and its companion packages always move together; never leave a script deeper than one folder or a companion without its script. Refuse while the game runs. current() -> which profile the folders match (or 'custom' + the differences). status() for humans. The fast switch must first make sure the fast pack is fresh (speedkit.fastmode.status/update_pack) - if fastmode.py is not finished when you test, test with a stub pack.
Also a compatibility test: import the real mods_switch.py as a module, point its SIMS/MODS/PARKED/MANIFEST constants at your fake tree, and check both directions: SpeedKit fast -> mods_switch full restores everything; mods_switch lean -> SpeedKit full restores everything; no file lost, no duplicate left, manifest consistent. Measure on the real folders (read-only): what switch('fast') would move right now from the current studio state (counts, GB).` },
  { key: 'merge', prompt: `COMPONENT "merge": speedkit/merge.py - the script-safe auto-merger and the download inbox.
(1) plan_merge(lib, roots=('Mods','Mods_parked'), target_bytes=1_000_000_000, max_bytes=1_900_000_000) -> groups of loose packages to merge. Never merge: .ts4script, never_merge() companions (core/addon/orphan/weak/broken), load_order_sensitive() names, packages that already are S4S merges (contain 0x7FB6AD8A), packages with errors, packages any of whose keys conflict (different content) with another package (use speedkit.hashing to decide identical vs conflicting), 'tuning' packages mixed with CC (tuning only merges with tuning from the same folder), the fast pack/SpeedKit files, FitStudio/. Group by category (CAS CC / BuildBuy / tuning / sliders+presets / other) and folder; order catalog records (CASP, THUM, OBJD, COBJ, SimData, XML, STBL) first in each merged file. Identical duplicate resources are written once. Output files 'Mods\\SpeedKit Merged\\<Category>_NNN.package' (or the same folder under Mods_parked if the sources are parked, so the other tool's manifest stays valid: if any source is parked, the merged file goes to Mods_parked at the matching rel and is ADDED to Mods_parked\\_manifest.json so 'full' restores it; if the sources are split across roots, do not merge that group). Each merged file carries an S4S manifest (speedkit.manifest.build_flat) listing every source so Sims 4 Studio can unmerge it.
(2) apply_merge(plan, lib, dry_run=True, quarantine_home=None) - write each merged file to a .writing temp, re-read and verify every resource bit-exact against its source, then Journal kind 'merge': put_new the merged file, quarantine the sources; afterwards rescan and check the invariant that the content the game uses for every key is unchanged (like dedup.apply; undo automatically on mismatch).
(3) Inbox: SIMS\\SpeedKit\\Inbox (outside Mods; create on first use). process_inbox(lib, dry_run=True): for each dropped item - .zip archives are extracted with zipfile (.rar/.7z: report 'extract it first'); .ts4script files (and the .package files shipped alongside them in the same download, which are their companions) go to Mods\\<download name>\\ (one folder deep) untouched; standalone .package CC is checked against the library: resources identical to library copies are dropped, packages with conflicts go to Mods\\SpeedKit Loose\\ unmerged (and are listed in the report), the rest are merged into 'Mods\\SpeedKit Merged\\New_NNN.package' (appending to the newest one below target size by writing a new version and quarantining the old). Items processed are moved to SIMS\\SpeedKit\\Inbox\\_done\\<date>\\. Journal kind 'inbox'. Report what went where.
Measure on the real library (read-only): what plan_merge would do today (groups, files, GB) - expected small, since most CC is already merged; say so honestly.` },
  { key: 'graphics', prompt: `COMPONENT "graphics": extend speedkit/settings.py (the wave-1 settings component; you may edit settings.py, launch.py and their tests/docs) with the MAX-QUALITY-WITHOUT-LAG graphics fix the user asked for: "keep graphics at highest but fix the lag".
Facts (research + wave-1 settings review): ConfigOverride\\GraphicsRules.sgr is Simp4Sims 'SGR Full' 2021; versus stock it sets RenderSimLODDistances ~3000 (stock 25/50/100/1000), ObjectSizeCullFactor 9999 (stock 200), far ClipPlaneDistances 9999 (stock 1000/1500), ObjectLODBias 0 (stock 0.6666), sim textures 2048 at every LOD (stock 2048/1024/512/128), shadow maps 5120 (stock 2048 VeryHigh), FSAALevel 512 (stock 8), mirror/water reflection distances 8-12x, TerrainLODBoost 6 (stock 1); it turns SSAO and depth of field off. Even Simp's Setters 'Ultimate Performance' preset keeps sims at full detail to ~9 km (ObjectSizeCullFactor -1) - so presets are not the answer.
Build graphics_use_tuned(dry_run=True): produce 'SpeedKit Max Quality' rules = the user's current SGR Full file with ONLY the lag-causing values brought back to sane, still-high-end values at the quality levels the user runs (Options.ini says Ultra/VeryHigh everywhere; keep them): sim LOD distances = 2x stock (so sims stay full-detail farther than stock but not to the horizon), ObjectSizeCullFactor = stock 200, ObjectLODBias = stock, far clip = stock for that level, FSAA = 8 (stock max; 512 is not a real level), shadow map 4096 (above stock 2048, below 5120), reflection distances 2x stock, TerrainLODBoost 2, sim texture LODs = 2048/2048/1024/512 (sharper than stock up close), everything else in SGR Full unchanged (keep its visual improvements). Do it as a minimal textual patch of the property assignments in the .sgr (so the file stays SGR Full + a header comment 'Tuned by SpeedKit'), then evaluate the result with the existing SGR evaluator at the user's levels and assert every intended value and that nothing else changed. Install it through Journal kind 'settings' (replace ConfigOverride\\GraphicsRules.sgr; keep the original in quarantine; graphics_restore undoes). Idempotent: running it twice changes nothing; if the user later replaces the file, status shows it. Also make graphics_status() report 'SpeedKit Max Quality' when active. Do NOT change Options.ini in-game settings (the user wants highest quality) - leave options_apply available but not used by default. Tests on a FAKE tree with copies of the user's ConfigOverride and Simps_GraphicsRules_Setters files; report the before/after values table at the user's levels (read-only on the real files).` },
]

phase('Build')
const built = await pipeline(
  COMPONENTS,
  c => agent(`${CONTEXT}\n\n${c.prompt}\n\nWhen done, run your tests (and the whole suite) and report in the required structure.`,
    { label: `build:${c.key}`, phase: 'Build', schema: RESULT }),
  (b, c) => agent(`${CONTEXT}\n\nYou are an independent, adversarial reviewer of the SpeedKit component "${c.key}". Its builder reported:\n${JSON.stringify(b)}\n\nThe spec was:\n${c.prompt}\n\nFind real defects and FIX the ones you confirm (in that component's own files). Read every line. Hunt for: data-safety holes (writes outside a Journal, deleting, touching .ts4script/companions/saves, missing game-running or dry-run guards, anything that could lose a mod or make a save lose CC in fast mode), coexistence bugs with the other chat's mods_switch.py and its manifest, correctness (signed/unsigned instances, deleted entries, RefPack, duplicate keys in one package, load-order/winner mistakes, partial failures and undo), API mismatches with the spec, and tests that pass without testing anything. Add adversarial tests on a FAKE tree under E:\\\\speedkit_test\\\\${c.key}_review, fix, re-run the whole suite, report.`,
    { label: `review:${c.key}`, phase: 'Review', schema: REVIEW }).then(r => ({ key: c.key, built: b, review: r })),
)

phase('Integrate')
const integ = await agent(`${CONTEXT}\n\nAll components are built and reviewed:\n${JSON.stringify(built.filter(Boolean).map(x => ({ key: x.key, api: x.built && x.built.public_api, notes: x.built && x.built.notes_for_integration, verdict: x.review && x.review.verdict, risks: x.review && x.review.remaining_risks })))}\n\nINTEGRATION TASK:
(1) speedkit/__main__.py - one CLI 'python -m speedkit <command>' over every component: status (profile, graphics, memory, fast-pack freshness, monitor installed, last load times from SIMS\\SpeedKit\\reports\\loadtimes.csv), scan, report, play [fast|full|studio] (the ONE-CLICK path, see 2), profile <name>, fastpack build|update|status|verify, usedpack ..., dedup plan|apply [--quarantine E:]|undo, merge plan|apply, inbox, graphics status|tuned|stock|restore, caches ..., monitor build|install|uninstall, journals, undo <id>, preflight. Every changing command is a dry run unless --apply is given, EXCEPT 'play', which is the user's one-click action and applies its steps.
(2) play(profile='fast'): if the game already runs -> say so and stop. Else, in order: scan the library (incremental); make sure SpeedKit Monitor is built+installed (install if missing/outdated); make sure graphics are 'SpeedKit Max Quality' (install if the active rules are SGR Full or stock-with-SGR-leftovers; never downgrade a user's other custom file silently - report it); for 'fast': make sure the fast pack is fresh (update or build it; show progress), switch profile; for 'full'/'studio': switch profile; run preflight and print its warnings in plain words (e.g. 'Chrome is using 20 GB of memory - close it for a much faster start'); launch the game via speedkit.launch (writes launch_time.json). Each step prints one short line. Errors print a plain explanation and leave everything consistent (journals). 
(3) One-click launchers in the project folder AND on the user's Desktop (C:\\Users\\basim\\Desktop - create only these files there, do not touch anything else): 'Sims 4 - Play FAST.bat' (python -m speedkit play fast), 'Sims 4 - Play with ALL CC.bat' (play full), 'Sims 4 - SpeedKit menu.bat' (a numbered menu: status, play fast/full/studio, add downloads from Inbox, free disk space (dedup plan then apply with quarantine on E:), undo last change, open reports folder). Batch files must work from any cwd (cd /d to the project), pause on error, and use the 'python' on PATH.
(4) speedkit/report.py -> SIMS\\SpeedKit\\reports\\library_report.html (self-contained, readable): library size, CAS parts full vs fast, duplicates removable, conflicts, script tuning buried in merges, orphans needing XML Injector/Pose Player, Cumshine not loading (.py only), the 20 lighting variants, missing CC worn by sims (top households), graphics before/after table, memory warnings, load-time history from loadtimes.csv.
(5) README.md in plain language for a non-technical user (what to click, what each launcher does, how to undo, where things are) + docs/architecture.md for developers.
Writing to the real Sims folder is NOT allowed for you either (only the Desktop .bat files and project files); test play() end-to-end on a FAKE tree with a fake exe (a .bat under E:\\speedkit_test\\integration) and make every real-folder command you try a dry run. Keep the whole test suite passing and add tests/test_cli*.py.`,
  { label: 'integrate', phase: 'Integrate', schema: RESULT })

phase('Audit')
const audit = await agent(`${CONTEXT}\n\nFINAL END-TO-END AUDIT of the whole SpeedKit (all components + the CLI/launchers the integrator reported: ${JSON.stringify(integ)}).\nBuild a realistic FAKE Sims tree under E:\\\\speedkit_test\\\\e2e: Mods + Mods_parked in the SAME layout as the real one today (the other chat's studio set in Mods, the rest parked with a manifest like theirs), with copies of ~30 real packages of every kind (a few sim/ merged packs of the smallest sizes, script mods with their companion packages, sliders, lighting variants, WW animation pack copies if small enough, else synthetic), copies of 1-2 real saves and some Tray files, a fake exe. Then run the real user flows through the CLI against the fake tree (use environment variables or parameters the CLI supports for the tree; if it cannot be pointed at a fake tree, that is a critical finding - fix it): play fast -> play full -> play studio -> the other chat's mods_switch.py lean/full (import it and patch its constants) -> play fast again -> dedup apply -> merge/inbox with a dropped download -> undo of each journal. After every step assert: no file lost or duplicated (compare a full file inventory with hashes to the start), .ts4script contents untouched, every script mod at depth <= 1 with its companions, saves/Tray untouched, manifest consistent, fast profile loads < 5% of the CAS parts of full while every CAS part referenced by the saves is still loaded (compute from the fake tree), the game-running refusal works (simulate with a stub), and undo restores the exact starting inventory. Fix every defect you find (in any SpeedKit file except dbpf/library/journal - report those), re-run the suite, and report findings, fixes and remaining risks.`,
  { label: 'audit:e2e', phase: 'Audit', schema: REVIEW })

return { built: built.filter(Boolean), integ, audit }
